//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_420_Pankov.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TournamentDB_420_PankovEntities : DbContext
    {
        public TournamentDB_420_PankovEntities()
            : base("name=TournamentDB_420_PankovEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessLevel> AccessLevel { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Matches> Matches { get; set; }
        public virtual DbSet<Organizers> Organizers { get; set; }
        public virtual DbSet<Participants> Participants { get; set; }
        public virtual DbSet<Registrations> Registrations { get; set; }
        public virtual DbSet<RoleInTeam> RoleInTeam { get; set; }
        public virtual DbSet<Spectators> Spectators { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tournaments> Tournaments { get; set; }
        public virtual DbSet<TournamentStandings> TournamentStandings { get; set; }
        public virtual DbSet<TournamentStatistics> TournamentStatistics { get; set; }
        public virtual DbSet<RegStatus> RegStatus { get; set; }
    }
}
