//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_420_Pankov.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registrations
    {
        public int RegistrationID { get; set; }
        public int ParticipantID { get; set; }
        public int TournamentID { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public int RegStatusID { get; set; }
        public string PreferredRoles { get; set; }
    
        public virtual Participants Participants { get; set; }
        public virtual Tournaments Tournaments { get; set; }
        public virtual RegStatus RegStatus { get; set; }
    }
}
