//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_420_Pankov.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegStatus
    {
        public int RegStatusID { get; set; }
        public string Name { get; set; }
    
        public virtual Registrations Registrations { get; set; }
    }
}
