//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_420_Pankov.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentStatistics
    {
        public int StatisticID { get; set; }
        public int TournamentID { get; set; }
        public int MatchesCount { get; set; }
        public int TotalDurationMinutes { get; set; }
        public Nullable<int> BestPlayerParticipantID { get; set; }
    
        public virtual Participants Participants { get; set; }
        public virtual Tournaments Tournaments { get; set; }
    }
}
